/*

 ██████╗██████╗ ██╗   ██╗██████╗ ████████╗███████╗ ██████╗ ██╗     ██╗ ██████╗
██╔════╝██╔══██╗╚██╗ ██╔╝██╔══██╗╚══██╔══╝██╔════╝██╔═══██╗██║     ██║██╔═══██╗
██║     ██████╔╝ ╚████╔╝ ██████╔╝   ██║   █████╗  ██║   ██║██║     ██║██║   ██║
██║     ██╔══██╗  ╚██╔╝  ██╔═══╝    ██║   ██╔══╝  ██║   ██║██║     ██║██║   ██║
╚██████╗██║  ██║   ██║   ██║        ██║   ██║     ╚██████╔╝███████╗██║╚██████╔╝
 ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚══════╝╚═╝ ╚═════╝

*/

// Auto-generated by Google for the Apps Script library deployment
const VERSION = "19";

/* -------------------------------------------------------------------------- */
/*                                  CONSTANTS                                 */
/* -------------------------------------------------------------------------- */

const BALANCE_OF_SIGHASH = "70a08231"; // this is keccak256("balanceOf(address)")
const COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3";
const DATE_FORMAT = "MMM, d yyyy HH:mm:ss"; // e.g. "Oct, 17 2025 12:00:00"
const TIMEZONE = "UTC";

// Retry mechanism configuration
const RETRY_BACKOFF_MULTIPLIER = 2;
const RETRY_INITIAL_DELAY_MS = 1000;
const RETRY_MAX_ATTEMPTS = 3;
const RETRY_MAX_DELAY_MS = 32000;
const RETRY_STATUS_CODES = [429, 500, 502, 503, 504];

/* -------------------------------------------------------------------------- */
/*                                    SETUP                                   */
/* -------------------------------------------------------------------------- */

/**
 * If you forked this file, you have to set the CoinGecko API key here.
 *
 * @see {@link https://support.coingecko.com/hc/en-us/articles/21880397454233-User-Guide-How-to-sign-up-for-CoinGecko-Demo-API-and-generate-an-API-key}
 */
const COINGECKO_API_KEY = "ADD_YOUR_API_KEY_HERE";

/**
 * If you forked this file, you have to set the RouteMesh API key here.
 *
 * @see {@link https://routeme.sh}
 */
const ROUTEMESH_API_KEY = "ADD_YOUR_API_KEY_HERE";

/**
 * Alternatively, if you are using this as a library, you can set the API keys
 * by calling these functions.
 */
function setCoinGeckoAPIKey(apiKey) {
  const properties = PropertiesService.getScriptProperties();
  properties.setProperty("COINGECKO_API_KEY", apiKey);
}

function setRouteMeshAPIKey(apiKey) {
  const properties = PropertiesService.getScriptProperties();
  properties.setProperty("ROUTEMESH_API_KEY", apiKey);
}

/* -------------------------------------------------------------------------- */
/*                            SPREADSHEET FUNCTIONS                           */
/* -------------------------------------------------------------------------- */

/**
 * Queries the CoinGecko API to obtain the current fiat price for all cryptocurrencies in the spreadsheet.
 *
 * @see {@link https://docs.coingecko.com/reference/simple-price}
 */
function GET_ALL_PRICES(fiat = Default.fiat) {
  // Read the symbols from the spreadsheet.
  const spreadsheet = SpreadsheetApp.getActive();
  const symbolsRange = spreadsheet.getRangeByName(NamedRange.symbols);
  const symbols = symbolsRange.getValues().flat();
  const normalizedSymbols = symbols.map((symbol) => normalizeSymbol_(symbol));

  // Map symbols to their CoinGecko IDs
  const coinIdsByRow = normalizedSymbols.map((symbol) => (symbol ? CoinGeckoId[symbol] : null));
  const coins = Array.from(new Set(coinIdsByRow.filter(Boolean))); // remove undefined values and dedupe

  // Load the existing prices range.
  const pricesSheet = spreadsheet.getSheetByName(Sheet.dataPrices);
  const pricesRange = pricesSheet.getRange(NamedRange.prices);
  const pricesValues = pricesRange.getValues();

  if (pricesValues.length !== symbols.length) {
    throwError(
      `GET_ALL_PRICES: SYMBOLS range row count (${symbols.length}) must match PRICES range row count (${pricesValues.length})`,
    );
  }

  // Construct the API URL.
  const options = { muteHttpExceptions: true };

  // Refresh the "Script Last Run At" cell.
  refreshScriptLastRunAt_();

  try {
    let json = {};

    if (coins.length > 0) {
      let url = COINGECKO_BASE_URL + "/simple/price";
      url += "?x_cg_demo_api_key=" + getCoinGeckoAPIKey_();
      url += "&ids=" + coins.join(",");
      url += "&vs_currencies=" + fiat;

      const httpResponse = fetchWithRetry_(url, options);
      const responseText = validateJSONResponse_(httpResponse, "GET_ALL_PRICES");

      try {
        json = JSON.parse(responseText);
      } catch (parseError) {
        const preview = responseText.substring(0, 500);
        throw new Error(
          `GET_ALL_PRICES: Failed to parse JSON. Response preview: ${preview}${responseText.length > 500 ? "..." : ""}`,
        );
      }

      handleJSONErrors_(json);
    }

    const prices = [];
    for (let i = 0; i < normalizedSymbols.length; i++) {
      const symbol = normalizedSymbols[i];
      const coinId = coinIdsByRow[i];

      if (!symbol) {
        prices.push([""]);
        continue;
      }

      if (!coinId) {
        prices.push([`Unknown symbol: ${symbol}`]);
        continue;
      }

      const value = json[coinId];

      // CoinGecko returns "{}" for some coins, e.g. listed but not launched
      if (!value || Object.keys(value).length === 0) {
        console.warn("Could not access price data for %s", coinId);
        prices.push(pricesValues[i]);
      } else {
        const price = json[coinId][fiat];
        prices.push([price]);
      }
    }
    // Update the prices range
    pricesRange.setValues(prices);

    // Refresh the "Prices Last Updated At" cell.
    refreshPricesLastUpdatedAt_();

    // Clear the error from the "Error" cell.
    spreadsheet.getRangeByName(NamedRange.pricesError).setValue("No Error");
  } catch (error) {
    throwError(error);
  }
}

/**
 * Makes a JSON-RPC call to the blockchain to get the ERC-20 token balance of an account.
 */
function GET_ERC20_BALANCE(
  chain = ChainId.ethereum,
  tokenSymbol = Default.token,
  account = Default.account,
) {
  const chainID = getChainID_(chain);
  const url = getRPC_(chainID);
  const token = getToken_(chainID, tokenSymbol);

  // We add 24 zeroes to left-pad the address with 12 bytes such that in total there are 32 bytes after
  // the signature hash. Recall that an Ethereum address has 20 bytes.
  const call = {
    data: "0x" + BALANCE_OF_SIGHASH + "0".repeat(24) + account.slice(2),
    from: account,
    to: token.address,
  };
  const options = {
    contentType: "application/json",
    method: "POST",
    muteHttpExceptions: true,
    payload: JSON.stringify({
      id: 1,
      jsonrpc: "2.0",
      method: "eth_call",
      params: [call, "latest"],
    }),
  };
  const httpResponse = fetchWithRetry_(url, options);
  const responseText = validateJSONResponse_(httpResponse, "GET_ERC20_BALANCE");

  let json;
  try {
    json = JSON.parse(responseText);
  } catch (parseError) {
    const preview = responseText.substring(0, 500);
    throw new Error(
      `GET_ERC20_BALANCE: Failed to parse JSON. Response preview: ${preview}${responseText.length > 500 ? "..." : ""}`,
    );
  }

  handleJSONErrors_(json);

  if (!json.result) {
    throw new Error("GET_ERC20_BALANCE: No balance returned");
  }
  const hexBalance = json.result;
  return formatUnits_(fromHex_(hexBalance), token.decimals);
}

/**
 * Makes a JSON-RPC call to an EVM blockchain to get the native asset balance of an account.
 */
function GET_NATIVE_BALANCE(chain = ChainId.ethereum, account = Default.account) {
  const chainID = getChainID_(chain);
  const url = getRPC_(chainID);
  const options = {
    contentType: "application/json",
    method: "POST",
    muteHttpExceptions: true,
    payload: JSON.stringify({
      id: 1,
      jsonrpc: "2.0",
      method: "eth_getBalance",
      params: [account, "latest"],
    }),
  };

  const httpResponse = fetchWithRetry_(url, options);
  const responseText = validateJSONResponse_(httpResponse, "GET_NATIVE_BALANCE");

  let json;
  try {
    json = JSON.parse(responseText);
  } catch (parseError) {
    const preview = responseText.substring(0, 500);
    throw new Error(
      `GET_NATIVE_BALANCE: Failed to parse JSON. Response preview: ${preview}${responseText.length > 500 ? "..." : ""}`,
    );
  }

  handleJSONErrors_(json);

  if (!json.result) {
    throw new Error("GET_NATIVE_BALANCE: No balance returned");
  }
  const hexBalance = json.result;
  return formatUnits_(fromHex_(hexBalance), 18);
}

/**
 * Queries the CoinGecko API to obtain the current fiat price of the given cryptocurrency.
 *
 * @see {@link https://docs.coingecko.com/reference/simple-price}
 */
function GET_PRICE(coinId = Default.coin, fiat = Default.fiat) {
  let url = COINGECKO_BASE_URL + "/simple/price";
  url += "?x_cg_demo_api_key=" + getCoinGeckoAPIKey_();
  url += "&ids=" + coinId;
  url += "&vs_currencies=" + fiat;
  const options = { muteHttpExceptions: true };

  const httpResponse = fetchWithRetry_(url, options);
  const responseText = validateJSONResponse_(httpResponse, "GET_PRICE");

  let json;
  try {
    json = JSON.parse(responseText);
  } catch (parseError) {
    const preview = responseText.substring(0, 500);
    throw new Error(
      `GET_PRICE: Failed to parse JSON. Response preview: ${preview}${responseText.length > 500 ? "..." : ""}`,
    );
  }

  handleJSONErrors_(json);

  if (!json[coinId] || !json[coinId][fiat]) {
    throw new Error("GET_PRICE: No price data returned");
  }
  return json[coinId][fiat];
}

/* -------------------------------------------------------------------------- */
/*                               INTERNAL LOGIC                               */
/* -------------------------------------------------------------------------- */

/* ----------------------------- Error Handling ----------------------------- */

/**
 * @see https://support.coingecko.com/hc/en-us/articles/4538787440153-Why-am-I-getting-errors-with-a-status-code-429
 */
function handleJSONErrors_(json) {
  // CoinGecko API Rate Limit
  if (json?.status?.error_code === 429) {
    throw new Error("CoinGecko API rate limit exceeded");
  }
  // Other CoinGecko API error
  if (json?.status?.error_code) {
    throw new Error("Unknown CoinGecko API error");
  }
}

function throwError(message) {
  const spreadsheet = SpreadsheetApp.getActive();
  spreadsheet.getRangeByName(NamedRange.pricesError).setValue(message);
  throw new Error(message);
}

/* ------------------------------ HTTP & Retry ------------------------------ */

/**
 * Calculates the delay for exponential backoff with jitter.
 *
 * @param {number} attempt - The current attempt number (0-indexed)
 * @param {number} initialDelay - Initial delay in milliseconds
 * @param {number} maxDelay - Maximum delay in milliseconds
 * @param {number} multiplier - Backoff multiplier
 * @returns {number} Delay in milliseconds
 */
function calculateBackoffDelay_(attempt, initialDelay, maxDelay, multiplier) {
  // Calculate exponential backoff: initialDelay * (multiplier ^ attempt)
  const exponentialDelay = initialDelay * multiplier ** attempt;

  // Cap at maxDelay
  const cappedDelay = Math.min(exponentialDelay, maxDelay);

  // Add jitter: random value between 80% and 120% of the delay
  const jitter = 0.8 + Math.random() * 0.4;

  return Math.floor(cappedDelay * jitter);
}

/**
 * Fetches a URL with retry logic and exponential backoff.
 *
 * @param {string} url - The URL to fetch
 * @param {object} options - Options to pass to UrlFetchApp.fetch()
 * @param {object} config - Retry configuration (optional)
 * @returns {HTTPResponse} The HTTP response object
 */
function fetchWithRetry_(url, options, config = {}) {
  const maxAttempts = config.maxAttempts || RETRY_MAX_ATTEMPTS;
  const initialDelay = config.initialDelayMs || RETRY_INITIAL_DELAY_MS;
  const maxDelay = config.maxDelayMs || RETRY_MAX_DELAY_MS;
  const backoffMultiplier = config.backoffMultiplier || RETRY_BACKOFF_MULTIPLIER;
  const retryableStatusCodes = config.retryableStatusCodes || RETRY_STATUS_CODES;

  let lastError;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      const response = UrlFetchApp.fetch(url, options);
      const statusCode = response.getResponseCode();

      // Check for client errors (4xx) - these should not be retried
      if (statusCode >= 400 && statusCode < 500) {
        const preview = response.getContentText().substring(0, 200);
        throw new Error(
          `HTTP ${statusCode} client error - ${preview}${response.getContentText().length > 200 ? "..." : ""}`,
        );
      }

      // Check if we should retry based on status code
      if (retryableStatusCodes.includes(statusCode)) {
        lastError = new Error(`HTTP ${statusCode} error`);

        if (attempt < maxAttempts - 1) {
          const delay = calculateBackoffDelay_(attempt, initialDelay, maxDelay, backoffMultiplier);
          console.warn(
            `Attempt ${attempt + 1} failed with status ${statusCode}, retrying in ${delay}ms...`,
          );
          Utilities.sleep(delay);
          continue;
        }
      }

      // Success or non-retryable status code
      return response;
    } catch (error) {
      lastError = error;

      if (attempt < maxAttempts - 1) {
        const delay = calculateBackoffDelay_(attempt, initialDelay, maxDelay, backoffMultiplier);
        console.warn(
          `Attempt ${attempt + 1} failed with error: ${error.message}, retrying in ${delay}ms...`,
        );
        Utilities.sleep(delay);
      }
    }
  }

  // All retries exhausted
  throw new Error(`Failed after ${maxAttempts} attempts: ${lastError.message}`);
}

/* --------------------------------- Helpers -------------------------------- */

/**
 * Validates that a response contains valid JSON and not HTML.
 *
 * @param {HTTPResponse} response - The HTTP response object
 * @param {string} context - Context string for error messages (e.g., "GET_ALL_PRICES")
 * @throws {Error} If response appears to be HTML or invalid JSON
 * @returns {string} The response content text
 */
function validateJSONResponse_(response, context) {
  const statusCode = response.getResponseCode();
  const contentType = response.getHeaders()["Content-Type"] || "";
  const text = response.getContentText();

  // Check for HTTP error codes that should fail immediately
  if (statusCode >= 400 && statusCode < 500) {
    const preview = text.substring(0, 200).replace(/\n/g, " ");
    throw new Error(
      `${context}: HTTP ${statusCode} error - ${preview}${text.length > 200 ? "..." : ""}`,
    );
  }

  // Check if response is HTML instead of JSON
  const trimmedText = text.trim();
  if (trimmedText.startsWith("<!DOCTYPE") || trimmedText.startsWith("<html")) {
    const preview = text.substring(0, 200).replace(/\n/g, " ");
    throw new Error(
      `${context}: Received HTML instead of JSON (status ${statusCode}). Response: ${preview}${text.length > 200 ? "..." : ""}`,
    );
  }

  // Check content type if present
  if (
    contentType &&
    !contentType.includes("application/json") &&
    !contentType.includes("text/plain")
  ) {
    throw new Error(
      `${context}: Unexpected content type "${contentType}" (expected application/json)`,
    );
  }

  // Check for empty response body
  if (!trimmedText) {
    throw new Error(
      `${context}: Empty response from server (status ${statusCode}, content-type: ${contentType || "none"})`,
    );
  }

  return text;
}

function normalizeSymbol_(symbol) {
  if (symbol === null || symbol === undefined) {
    return "";
  }
  const text = String(symbol).trim();
  if (!text) {
    return "";
  }
  return text.toUpperCase();
}

function fromHex_(value) {
  if (typeof BigInt !== "function") {
    throw new Error("BigInt is not available in this Apps Script runtime. Enable V8.");
  }
  if (!value || value === "0x" || value === "0X") {
    return BigInt("0");
  }
  return BigInt(String(value));
}

function formatUnits_(value, decimals) {
  if (typeof BigInt !== "function") {
    throw new Error("BigInt is not available in this Apps Script runtime. Enable V8.");
  }
  if (!Number.isInteger(decimals) || decimals < 0) {
    throw new Error(`Invalid token decimals: ${decimals}`);
  }
  const zero = BigInt("0");
  const negative = value < zero;
  const base = BigInt("10") ** BigInt(String(decimals));
  const abs = negative ? -value : value;
  const whole = abs / base;
  const fraction = abs % base;

  let text;
  if (decimals === 0 || fraction === zero) {
    text = `${negative ? "-" : ""}${whole.toString()}`;
  } else {
    let fractionText = fraction.toString().padStart(decimals, "0");
    fractionText = fractionText.replace(/0+$/, "");
    text = `${negative ? "-" : ""}${whole.toString()}.${fractionText}`;
  }

  const result = Number(text);
  if (!Number.isFinite(result)) {
    throw new Error("Balance exceeds JavaScript Number range");
  }
  const maxSafe = BigInt(String(Number.MAX_SAFE_INTEGER));
  if (abs > maxSafe * base) {
    console.warn("Balance exceeds JS safe integer precision; result may be rounded");
  }
  return result;
}

function getChainID_(chainIdOrName) {
  if (typeof chainIdOrName === "number") {
    return chainIdOrName;
  }
  const chainId = ChainNameMap[chainIdOrName.toLowerCase()];
  if (!chainId) {
    throw new Error(`Unknown chain ID or chain name: ${chainIdOrName}`);
  }
  return chainId;
}

function getCoinGeckoAPIKey_() {
  if (COINGECKO_API_KEY !== "ADD_YOUR_API_KEY_HERE") {
    return COINGECKO_API_KEY;
  }
  const properties = PropertiesService.getScriptProperties();
  const apiKey = properties.getProperty("COINGECKO_API_KEY");
  if (!apiKey) {
    throw new Error("CoinGecko API key not set");
  }
  return apiKey;
}

function getRPC_(chainID = ChainId.ethereum) {
  chainID = parseInt(chainID, 10);
  const routeMeshKey = getRouteMeshAPIKey_();
  if (routeMeshKey) {
    return `https://lb.routeme.sh/rpc/${chainID}/${routeMeshKey}`;
  }
  return RpcUrl[chainID] || RpcUrl.default;
}

function getRouteMeshAPIKey_() {
  if (ROUTEMESH_API_KEY !== "ADD_YOUR_API_KEY_HERE") {
    return ROUTEMESH_API_KEY;
  }
  const properties = PropertiesService.getScriptProperties();
  return properties.getProperty("ROUTEMESH_API_KEY");
}

function getToken_(chainID = ChainId.ethereum, symbol = Default.token) {
  chainID = parseInt(chainID, 10);
  const token = Token[symbol] || Token.default;
  // Some tokens exist on multiple chains.
  return token[chainID] || token.default || token;
}

function refreshPricesLastUpdatedAt_() {
  const cell = SpreadsheetApp.getActive().getRangeByName(NamedRange.pricesLastUpdatedAt);
  cell.setValue(Utilities.formatDate(new Date(), TIMEZONE, DATE_FORMAT));
}

function refreshScriptLastRunAt_() {
  const cell = SpreadsheetApp.getActive().getRangeByName(NamedRange.scriptLastRunAt);
  cell.setValue(Utilities.formatDate(new Date(), TIMEZONE, DATE_FORMAT));
}
